// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RFyI35IkAXVCLgfKiljT7dZjybRMRII',
    appId: '1:751303213812:web:dc0ad4c059f083cb5a94a1',
    messagingSenderId: '751303213812',
    projectId: 'flutter-chat-app-7524c',
    authDomain: 'flutter-chat-app-7524c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7524c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClXzvPiSfFiMHs4rt83oL0bPxaaiRMc8A',
    appId: '1:751303213812:android:64b71c39ba1b35a25a94a1',
    messagingSenderId: '751303213812',
    projectId: 'flutter-chat-app-7524c',
    storageBucket: 'flutter-chat-app-7524c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvd_igKm63F-PZWcaIZ8tdhO-JFEFVOy8',
    appId: '1:751303213812:ios:c71595a9932be7b35a94a1',
    messagingSenderId: '751303213812',
    projectId: 'flutter-chat-app-7524c',
    storageBucket: 'flutter-chat-app-7524c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvd_igKm63F-PZWcaIZ8tdhO-JFEFVOy8',
    appId: '1:751303213812:ios:551085929ee2d0bb5a94a1',
    messagingSenderId: '751303213812',
    projectId: 'flutter-chat-app-7524c',
    storageBucket: 'flutter-chat-app-7524c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
